server:
  shutdown: graceful
  port: 8892
  servlet:
    session:
      cookie:
        name: SSO-SESSIONID
  undertow:
    buffer-size: 1024
    direct-buffers: on
    always-set-keep-alive: true
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sparkzxl-resource-server
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://sparkzxl.mysql.rds.aliyuncs.com/authorization_server?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: zhouxinlei
    password: Zxl298828
  redis:
    host: 47.114.40.129
    port: 6379
    time-out: 28800
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: 200
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.github.sparkzxl.resource.infrastructure.entity
  custom:
    mapper-scan: com.github.sparkzxl.resource.infrastructure.mapper
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
knife4j:
  group-name: 资源保护应用
  base-package: com.github.sparkzxl.resource
  title: 资源保护应用
  description: 资源保护管理
  terms-of-service-url: https://www.sparksys.top
  version: 1.0
  license: Powered By sparkzxl
  licenseUrl: https://github.com/sparkzxl
  contact:
    url: https://github.com/sparkzxl
    name: zhouxinlei
    email: zhouxinlei298@163.com
  global-operation-parameters:
    - name: Authorization
      description: 客户端信息
      modelRef: String
      parameterType: header
      required: true
      defaultValue: "Bearer enVpaG91X3VpOnp1aWhvdV91aV9zZWNyZXQ="
security:
  oauth2:
    client:
      client-id: sparkzxl-resource
      client-secret: 123456
      user-authorization-uri: http://127.0.0.1:8801/oauth/authorize # 获取用户的授权码地址
      access-token-uri: http://127.0.0.1:8801/oauth/token # 获取访问令牌的地址
    resource:
      jwt:
        key-uri: http://127.0.0.1:8801/oauth/token_key
